// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: rewardDayStatsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RewardDayStatsService service

func NewRewardDayStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RewardDayStatsService service

type RewardDayStatsService interface {
	// 查询满减送活动每日统计
	Search(ctx context.Context, in *RewardDayStatsWhere, opts ...client.CallOption) (*RewardDayStatsResponse, error)
	// 获取满减送活动每日统计
	Get(ctx context.Context, in *RewardDayStatsWhere, opts ...client.CallOption) (*RewardDayStatsResponse, error)
}

type rewardDayStatsService struct {
	c    client.Client
	name string
}

func NewRewardDayStatsService(name string, c client.Client) RewardDayStatsService {
	return &rewardDayStatsService{
		c:    c,
		name: name,
	}
}

func (c *rewardDayStatsService) Search(ctx context.Context, in *RewardDayStatsWhere, opts ...client.CallOption) (*RewardDayStatsResponse, error) {
	req := c.c.NewRequest(c.name, "RewardDayStatsService.Search", in)
	out := new(RewardDayStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rewardDayStatsService) Get(ctx context.Context, in *RewardDayStatsWhere, opts ...client.CallOption) (*RewardDayStatsResponse, error) {
	req := c.c.NewRequest(c.name, "RewardDayStatsService.Get", in)
	out := new(RewardDayStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RewardDayStatsService service

type RewardDayStatsServiceHandler interface {
	// 查询满减送活动每日统计
	Search(context.Context, *RewardDayStatsWhere, *RewardDayStatsResponse) error
	// 获取满减送活动每日统计
	Get(context.Context, *RewardDayStatsWhere, *RewardDayStatsResponse) error
}

func RegisterRewardDayStatsServiceHandler(s server.Server, hdlr RewardDayStatsServiceHandler, opts ...server.HandlerOption) error {
	type rewardDayStatsService interface {
		Search(ctx context.Context, in *RewardDayStatsWhere, out *RewardDayStatsResponse) error
		Get(ctx context.Context, in *RewardDayStatsWhere, out *RewardDayStatsResponse) error
	}
	type RewardDayStatsService struct {
		rewardDayStatsService
	}
	h := &rewardDayStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RewardDayStatsService{h}, opts...))
}

type rewardDayStatsServiceHandler struct {
	RewardDayStatsServiceHandler
}

func (h *rewardDayStatsServiceHandler) Search(ctx context.Context, in *RewardDayStatsWhere, out *RewardDayStatsResponse) error {
	return h.RewardDayStatsServiceHandler.Search(ctx, in, out)
}

func (h *rewardDayStatsServiceHandler) Get(ctx context.Context, in *RewardDayStatsWhere, out *RewardDayStatsResponse) error {
	return h.RewardDayStatsServiceHandler.Get(ctx, in, out)
}
