// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: rewardGoodsStatsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RewardGoodsStatsService service

func NewRewardGoodsStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RewardGoodsStatsService service

type RewardGoodsStatsService interface {
	// 查询满减送活动用户购买的商品统计
	Search(ctx context.Context, in *RewardGoodsStatsWhere, opts ...client.CallOption) (*RewardGoodsStatsResponse, error)
	// 获取满减送活动用户购买的商品统计
	Get(ctx context.Context, in *RewardGoodsStatsWhere, opts ...client.CallOption) (*RewardGoodsStatsResponse, error)
}

type rewardGoodsStatsService struct {
	c    client.Client
	name string
}

func NewRewardGoodsStatsService(name string, c client.Client) RewardGoodsStatsService {
	return &rewardGoodsStatsService{
		c:    c,
		name: name,
	}
}

func (c *rewardGoodsStatsService) Search(ctx context.Context, in *RewardGoodsStatsWhere, opts ...client.CallOption) (*RewardGoodsStatsResponse, error) {
	req := c.c.NewRequest(c.name, "RewardGoodsStatsService.Search", in)
	out := new(RewardGoodsStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rewardGoodsStatsService) Get(ctx context.Context, in *RewardGoodsStatsWhere, opts ...client.CallOption) (*RewardGoodsStatsResponse, error) {
	req := c.c.NewRequest(c.name, "RewardGoodsStatsService.Get", in)
	out := new(RewardGoodsStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RewardGoodsStatsService service

type RewardGoodsStatsServiceHandler interface {
	// 查询满减送活动用户购买的商品统计
	Search(context.Context, *RewardGoodsStatsWhere, *RewardGoodsStatsResponse) error
	// 获取满减送活动用户购买的商品统计
	Get(context.Context, *RewardGoodsStatsWhere, *RewardGoodsStatsResponse) error
}

func RegisterRewardGoodsStatsServiceHandler(s server.Server, hdlr RewardGoodsStatsServiceHandler, opts ...server.HandlerOption) error {
	type rewardGoodsStatsService interface {
		Search(ctx context.Context, in *RewardGoodsStatsWhere, out *RewardGoodsStatsResponse) error
		Get(ctx context.Context, in *RewardGoodsStatsWhere, out *RewardGoodsStatsResponse) error
	}
	type RewardGoodsStatsService struct {
		rewardGoodsStatsService
	}
	h := &rewardGoodsStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RewardGoodsStatsService{h}, opts...))
}

type rewardGoodsStatsServiceHandler struct {
	RewardGoodsStatsServiceHandler
}

func (h *rewardGoodsStatsServiceHandler) Search(ctx context.Context, in *RewardGoodsStatsWhere, out *RewardGoodsStatsResponse) error {
	return h.RewardGoodsStatsServiceHandler.Search(ctx, in, out)
}

func (h *rewardGoodsStatsServiceHandler) Get(ctx context.Context, in *RewardGoodsStatsWhere, out *RewardGoodsStatsResponse) error {
	return h.RewardGoodsStatsServiceHandler.Get(ctx, in, out)
}
