// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: navItemService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NavItemService service

func NewNavItemServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NavItemService service

type NavItemService interface {
	Tree(ctx context.Context, in *NavItemWhere, opts ...client.CallOption) (*NavItemResponse, error)
}

type navItemService struct {
	c    client.Client
	name string
}

func NewNavItemService(name string, c client.Client) NavItemService {
	return &navItemService{
		c:    c,
		name: name,
	}
}

func (c *navItemService) Tree(ctx context.Context, in *NavItemWhere, opts ...client.CallOption) (*NavItemResponse, error) {
	req := c.c.NewRequest(c.name, "NavItemService.Tree", in)
	out := new(NavItemResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NavItemService service

type NavItemServiceHandler interface {
	Tree(context.Context, *NavItemWhere, *NavItemResponse) error
}

func RegisterNavItemServiceHandler(s server.Server, hdlr NavItemServiceHandler, opts ...server.HandlerOption) error {
	type navItemService interface {
		Tree(ctx context.Context, in *NavItemWhere, out *NavItemResponse) error
	}
	type NavItemService struct {
		navItemService
	}
	h := &navItemServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NavItemService{h}, opts...))
}

type navItemServiceHandler struct {
	NavItemServiceHandler
}

func (h *navItemServiceHandler) Tree(ctx context.Context, in *NavItemWhere, out *NavItemResponse) error {
	return h.NavItemServiceHandler.Tree(ctx, in, out)
}
