// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: navPositionService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NavPositionService service

func NewNavPositionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NavPositionService service

type NavPositionService interface {
	List(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error)
	Get(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error)
	Save(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error)
}

type navPositionService struct {
	c    client.Client
	name string
}

func NewNavPositionService(name string, c client.Client) NavPositionService {
	return &navPositionService{
		c:    c,
		name: name,
	}
}

func (c *navPositionService) List(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error) {
	req := c.c.NewRequest(c.name, "NavPositionService.List", in)
	out := new(NavPositionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navPositionService) Get(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error) {
	req := c.c.NewRequest(c.name, "NavPositionService.Get", in)
	out := new(NavPositionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navPositionService) Save(ctx context.Context, in *NavPositionWhere, opts ...client.CallOption) (*NavPositionResponse, error) {
	req := c.c.NewRequest(c.name, "NavPositionService.Save", in)
	out := new(NavPositionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NavPositionService service

type NavPositionServiceHandler interface {
	List(context.Context, *NavPositionWhere, *NavPositionResponse) error
	Get(context.Context, *NavPositionWhere, *NavPositionResponse) error
	Save(context.Context, *NavPositionWhere, *NavPositionResponse) error
}

func RegisterNavPositionServiceHandler(s server.Server, hdlr NavPositionServiceHandler, opts ...server.HandlerOption) error {
	type navPositionService interface {
		List(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error
		Get(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error
		Save(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error
	}
	type NavPositionService struct {
		navPositionService
	}
	h := &navPositionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NavPositionService{h}, opts...))
}

type navPositionServiceHandler struct {
	NavPositionServiceHandler
}

func (h *navPositionServiceHandler) List(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error {
	return h.NavPositionServiceHandler.List(ctx, in, out)
}

func (h *navPositionServiceHandler) Get(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error {
	return h.NavPositionServiceHandler.Get(ctx, in, out)
}

func (h *navPositionServiceHandler) Save(ctx context.Context, in *NavPositionWhere, out *NavPositionResponse) error {
	return h.NavPositionServiceHandler.Save(ctx, in, out)
}
