// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: timeConfigService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TimeConfigWhere struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessType string `protobuf:"bytes,1,opt,name=business_type,json=businessType,proto3" json:"business_type"`
	TimeType     int32  `protobuf:"varint,2,opt,name=time_type,json=timeType,proto3" json:"time_type"`
}

func (x *TimeConfigWhere) Reset() {
	*x = TimeConfigWhere{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeConfigService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeConfigWhere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeConfigWhere) ProtoMessage() {}

func (x *TimeConfigWhere) ProtoReflect() protoreflect.Message {
	mi := &file_timeConfigService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeConfigWhere.ProtoReflect.Descriptor instead.
func (*TimeConfigWhere) Descriptor() ([]byte, []int) {
	return file_timeConfigService_proto_rawDescGZIP(), []int{0}
}

func (x *TimeConfigWhere) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *TimeConfigWhere) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

type TimeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	BusinessType string `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type"`
	TimeType     int32  `protobuf:"varint,3,opt,name=time_type,json=timeType,proto3" json:"time_type"`
	FieldName    string `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name"`
	CreatedAt    string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt    string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	// @inject_tag: gorm:"foreignKey:TimeConfigId"
	TimeRanges []*TimeRange `protobuf:"bytes,7,rep,name=time_ranges,json=timeRanges,proto3" json:"time_ranges" gorm:"foreignKey:TimeConfigId"`
}

func (x *TimeConfig) Reset() {
	*x = TimeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeConfigService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeConfig) ProtoMessage() {}

func (x *TimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_timeConfigService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeConfig.ProtoReflect.Descriptor instead.
func (*TimeConfig) Descriptor() ([]byte, []int) {
	return file_timeConfigService_proto_rawDescGZIP(), []int{1}
}

func (x *TimeConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimeConfig) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *TimeConfig) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *TimeConfig) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *TimeConfig) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TimeConfig) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TimeConfig) GetTimeRanges() []*TimeRange {
	if x != nil {
		return x.TimeRanges
	}
	return nil
}

var File_timeConfigService_proto protoreflect.FileDescriptor

var file_timeConfigService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x1a, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0f, 0x54,
	0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x57, 0x68, 0x65, 0x72, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xf1, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x34,
	0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeConfigService_proto_rawDescOnce sync.Once
	file_timeConfigService_proto_rawDescData = file_timeConfigService_proto_rawDesc
)

func file_timeConfigService_proto_rawDescGZIP() []byte {
	file_timeConfigService_proto_rawDescOnce.Do(func() {
		file_timeConfigService_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeConfigService_proto_rawDescData)
	})
	return file_timeConfigService_proto_rawDescData
}

var file_timeConfigService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_timeConfigService_proto_goTypes = []interface{}{
	(*TimeConfigWhere)(nil), // 0: services.TimeConfigWhere
	(*TimeConfig)(nil),      // 1: services.TimeConfig
	(*TimeRange)(nil),       // 2: services.TimeRange
}
var file_timeConfigService_proto_depIdxs = []int32{
	2, // 0: services.TimeConfig.time_ranges:type_name -> services.TimeRange
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timeConfigService_proto_init() }
func file_timeConfigService_proto_init() {
	if File_timeConfigService_proto != nil {
		return
	}
	file_timeRangeService_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_timeConfigService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeConfigWhere); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeConfigService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeConfigService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timeConfigService_proto_goTypes,
		DependencyIndexes: file_timeConfigService_proto_depIdxs,
		MessageInfos:      file_timeConfigService_proto_msgTypes,
	}.Build()
	File_timeConfigService_proto = out.File
	file_timeConfigService_proto_rawDesc = nil
	file_timeConfigService_proto_goTypes = nil
	file_timeConfigService_proto_depIdxs = nil
}
