// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: groupStatsService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GroupStatsService service

func NewGroupStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GroupStatsService service

type GroupStatsService interface {
	// 查询活动汇总统计
	Search(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error)
	// 获取活动汇总统计
	Get(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error)
	// 获取活动汇总统计列表
	List(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error)
	// 重置统计
	Reset(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*GroupStatsResponse, error)
}

type groupStatsService struct {
	c    client.Client
	name string
}

func NewGroupStatsService(name string, c client.Client) GroupStatsService {
	return &groupStatsService{
		c:    c,
		name: name,
	}
}

func (c *groupStatsService) Search(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error) {
	req := c.c.NewRequest(c.name, "GroupStatsService.Search", in)
	out := new(GroupStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupStatsService) Get(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error) {
	req := c.c.NewRequest(c.name, "GroupStatsService.Get", in)
	out := new(GroupStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupStatsService) List(ctx context.Context, in *GroupStatsWhere, opts ...client.CallOption) (*GroupStatsResponse, error) {
	req := c.c.NewRequest(c.name, "GroupStatsService.List", in)
	out := new(GroupStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupStatsService) Reset(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*GroupStatsResponse, error) {
	req := c.c.NewRequest(c.name, "GroupStatsService.Reset", in)
	out := new(GroupStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GroupStatsService service

type GroupStatsServiceHandler interface {
	// 查询活动汇总统计
	Search(context.Context, *GroupStatsWhere, *GroupStatsResponse) error
	// 获取活动汇总统计
	Get(context.Context, *GroupStatsWhere, *GroupStatsResponse) error
	// 获取活动汇总统计列表
	List(context.Context, *GroupStatsWhere, *GroupStatsResponse) error
	// 重置统计
	Reset(context.Context, *common.Empty, *GroupStatsResponse) error
}

func RegisterGroupStatsServiceHandler(s server.Server, hdlr GroupStatsServiceHandler, opts ...server.HandlerOption) error {
	type groupStatsService interface {
		Search(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error
		Get(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error
		List(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error
		Reset(ctx context.Context, in *common.Empty, out *GroupStatsResponse) error
	}
	type GroupStatsService struct {
		groupStatsService
	}
	h := &groupStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GroupStatsService{h}, opts...))
}

type groupStatsServiceHandler struct {
	GroupStatsServiceHandler
}

func (h *groupStatsServiceHandler) Search(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error {
	return h.GroupStatsServiceHandler.Search(ctx, in, out)
}

func (h *groupStatsServiceHandler) Get(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error {
	return h.GroupStatsServiceHandler.Get(ctx, in, out)
}

func (h *groupStatsServiceHandler) List(ctx context.Context, in *GroupStatsWhere, out *GroupStatsResponse) error {
	return h.GroupStatsServiceHandler.List(ctx, in, out)
}

func (h *groupStatsServiceHandler) Reset(ctx context.Context, in *common.Empty, out *GroupStatsResponse) error {
	return h.GroupStatsServiceHandler.Reset(ctx, in, out)
}
