// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: foodService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Food struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ItemId   int64   `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id"`
	FoodType string  `protobuf:"bytes,3,opt,name=food_type,json=foodType,proto3" json:"food_type"`
	KindId   int64   `protobuf:"varint,4,opt,name=kind_id,json=kindId,proto3" json:"kind_id"`
	BoxFee   float32 `protobuf:"fixed32,5,opt,name=box_fee,json=boxFee,proto3" json:"box_fee"`
}

func (x *Food) Reset() {
	*x = Food{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foodService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_foodService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_foodService_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Food) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Food) GetFoodType() string {
	if x != nil {
		return x.FoodType
	}
	return ""
}

func (x *Food) GetKindId() int64 {
	if x != nil {
		return x.KindId
	}
	return 0
}

func (x *Food) GetBoxFee() float32 {
	if x != nil {
		return x.BoxFee
	}
	return 0
}

var File_foodService_proto protoreflect.FileDescriptor

var file_foodService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x7e, 0x0a,
	0x04, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6b,
	0x69, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6b, 0x69,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x78, 0x5f, 0x66, 0x65, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x62, 0x6f, 0x78, 0x46, 0x65, 0x65, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_foodService_proto_rawDescOnce sync.Once
	file_foodService_proto_rawDescData = file_foodService_proto_rawDesc
)

func file_foodService_proto_rawDescGZIP() []byte {
	file_foodService_proto_rawDescOnce.Do(func() {
		file_foodService_proto_rawDescData = protoimpl.X.CompressGZIP(file_foodService_proto_rawDescData)
	})
	return file_foodService_proto_rawDescData
}

var file_foodService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_foodService_proto_goTypes = []interface{}{
	(*Food)(nil), // 0: services.Food
}
var file_foodService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foodService_proto_init() }
func file_foodService_proto_init() {
	if File_foodService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foodService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Food); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foodService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foodService_proto_goTypes,
		DependencyIndexes: file_foodService_proto_depIdxs,
		MessageInfos:      file_foodService_proto_msgTypes,
	}.Build()
	File_foodService_proto = out.File
	file_foodService_proto_rawDesc = nil
	file_foodService_proto_goTypes = nil
	file_foodService_proto_depIdxs = nil
}
