// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: limitDiscountCustomerStatsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LimitDiscountCustomerStatsService service

func NewLimitDiscountCustomerStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LimitDiscountCustomerStatsService service

type LimitDiscountCustomerStatsService interface {
	// 查询限时折扣活动用户统计
	Search(ctx context.Context, in *LimitDiscountCustomerStatsWhere, opts ...client.CallOption) (*LimitDiscountCustomerStatsResponse, error)
	// 获取限时折扣活动用户统计
	Get(ctx context.Context, in *LimitDiscountCustomerStatsWhere, opts ...client.CallOption) (*LimitDiscountCustomerStatsResponse, error)
}

type limitDiscountCustomerStatsService struct {
	c    client.Client
	name string
}

func NewLimitDiscountCustomerStatsService(name string, c client.Client) LimitDiscountCustomerStatsService {
	return &limitDiscountCustomerStatsService{
		c:    c,
		name: name,
	}
}

func (c *limitDiscountCustomerStatsService) Search(ctx context.Context, in *LimitDiscountCustomerStatsWhere, opts ...client.CallOption) (*LimitDiscountCustomerStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountCustomerStatsService.Search", in)
	out := new(LimitDiscountCustomerStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitDiscountCustomerStatsService) Get(ctx context.Context, in *LimitDiscountCustomerStatsWhere, opts ...client.CallOption) (*LimitDiscountCustomerStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountCustomerStatsService.Get", in)
	out := new(LimitDiscountCustomerStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LimitDiscountCustomerStatsService service

type LimitDiscountCustomerStatsServiceHandler interface {
	// 查询限时折扣活动用户统计
	Search(context.Context, *LimitDiscountCustomerStatsWhere, *LimitDiscountCustomerStatsResponse) error
	// 获取限时折扣活动用户统计
	Get(context.Context, *LimitDiscountCustomerStatsWhere, *LimitDiscountCustomerStatsResponse) error
}

func RegisterLimitDiscountCustomerStatsServiceHandler(s server.Server, hdlr LimitDiscountCustomerStatsServiceHandler, opts ...server.HandlerOption) error {
	type limitDiscountCustomerStatsService interface {
		Search(ctx context.Context, in *LimitDiscountCustomerStatsWhere, out *LimitDiscountCustomerStatsResponse) error
		Get(ctx context.Context, in *LimitDiscountCustomerStatsWhere, out *LimitDiscountCustomerStatsResponse) error
	}
	type LimitDiscountCustomerStatsService struct {
		limitDiscountCustomerStatsService
	}
	h := &limitDiscountCustomerStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LimitDiscountCustomerStatsService{h}, opts...))
}

type limitDiscountCustomerStatsServiceHandler struct {
	LimitDiscountCustomerStatsServiceHandler
}

func (h *limitDiscountCustomerStatsServiceHandler) Search(ctx context.Context, in *LimitDiscountCustomerStatsWhere, out *LimitDiscountCustomerStatsResponse) error {
	return h.LimitDiscountCustomerStatsServiceHandler.Search(ctx, in, out)
}

func (h *limitDiscountCustomerStatsServiceHandler) Get(ctx context.Context, in *LimitDiscountCustomerStatsWhere, out *LimitDiscountCustomerStatsResponse) error {
	return h.LimitDiscountCustomerStatsServiceHandler.Get(ctx, in, out)
}
