// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: limitDiscountStatsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LimitDiscountStatsService service

func NewLimitDiscountStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LimitDiscountStatsService service

type LimitDiscountStatsService interface {
	// 查询限时折扣活动汇总统计
	Search(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error)
	// 获取限时折扣活动汇总统计
	Get(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error)
	// 重置限时折扣活动统计
	Reset(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error)
}

type limitDiscountStatsService struct {
	c    client.Client
	name string
}

func NewLimitDiscountStatsService(name string, c client.Client) LimitDiscountStatsService {
	return &limitDiscountStatsService{
		c:    c,
		name: name,
	}
}

func (c *limitDiscountStatsService) Search(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountStatsService.Search", in)
	out := new(LimitDiscountStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitDiscountStatsService) Get(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountStatsService.Get", in)
	out := new(LimitDiscountStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitDiscountStatsService) Reset(ctx context.Context, in *LimitDiscountStatsWhere, opts ...client.CallOption) (*LimitDiscountStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountStatsService.Reset", in)
	out := new(LimitDiscountStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LimitDiscountStatsService service

type LimitDiscountStatsServiceHandler interface {
	// 查询限时折扣活动汇总统计
	Search(context.Context, *LimitDiscountStatsWhere, *LimitDiscountStatsResponse) error
	// 获取限时折扣活动汇总统计
	Get(context.Context, *LimitDiscountStatsWhere, *LimitDiscountStatsResponse) error
	// 重置限时折扣活动统计
	Reset(context.Context, *LimitDiscountStatsWhere, *LimitDiscountStatsResponse) error
}

func RegisterLimitDiscountStatsServiceHandler(s server.Server, hdlr LimitDiscountStatsServiceHandler, opts ...server.HandlerOption) error {
	type limitDiscountStatsService interface {
		Search(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error
		Get(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error
		Reset(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error
	}
	type LimitDiscountStatsService struct {
		limitDiscountStatsService
	}
	h := &limitDiscountStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LimitDiscountStatsService{h}, opts...))
}

type limitDiscountStatsServiceHandler struct {
	LimitDiscountStatsServiceHandler
}

func (h *limitDiscountStatsServiceHandler) Search(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error {
	return h.LimitDiscountStatsServiceHandler.Search(ctx, in, out)
}

func (h *limitDiscountStatsServiceHandler) Get(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error {
	return h.LimitDiscountStatsServiceHandler.Get(ctx, in, out)
}

func (h *limitDiscountStatsServiceHandler) Reset(ctx context.Context, in *LimitDiscountStatsWhere, out *LimitDiscountStatsResponse) error {
	return h.LimitDiscountStatsServiceHandler.Reset(ctx, in, out)
}
