// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: limitDiscountDayStatsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LimitDiscountDayStatsService service

func NewLimitDiscountDayStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LimitDiscountDayStatsService service

type LimitDiscountDayStatsService interface {
	// 查询限时折扣活动每日统计
	Search(ctx context.Context, in *LimitDiscountDayStatsWhere, opts ...client.CallOption) (*LimitDiscountDayStatsResponse, error)
	// 获取限时折扣活动每日统计
	Get(ctx context.Context, in *LimitDiscountDayStatsWhere, opts ...client.CallOption) (*LimitDiscountDayStatsResponse, error)
}

type limitDiscountDayStatsService struct {
	c    client.Client
	name string
}

func NewLimitDiscountDayStatsService(name string, c client.Client) LimitDiscountDayStatsService {
	return &limitDiscountDayStatsService{
		c:    c,
		name: name,
	}
}

func (c *limitDiscountDayStatsService) Search(ctx context.Context, in *LimitDiscountDayStatsWhere, opts ...client.CallOption) (*LimitDiscountDayStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountDayStatsService.Search", in)
	out := new(LimitDiscountDayStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *limitDiscountDayStatsService) Get(ctx context.Context, in *LimitDiscountDayStatsWhere, opts ...client.CallOption) (*LimitDiscountDayStatsResponse, error) {
	req := c.c.NewRequest(c.name, "LimitDiscountDayStatsService.Get", in)
	out := new(LimitDiscountDayStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LimitDiscountDayStatsService service

type LimitDiscountDayStatsServiceHandler interface {
	// 查询限时折扣活动每日统计
	Search(context.Context, *LimitDiscountDayStatsWhere, *LimitDiscountDayStatsResponse) error
	// 获取限时折扣活动每日统计
	Get(context.Context, *LimitDiscountDayStatsWhere, *LimitDiscountDayStatsResponse) error
}

func RegisterLimitDiscountDayStatsServiceHandler(s server.Server, hdlr LimitDiscountDayStatsServiceHandler, opts ...server.HandlerOption) error {
	type limitDiscountDayStatsService interface {
		Search(ctx context.Context, in *LimitDiscountDayStatsWhere, out *LimitDiscountDayStatsResponse) error
		Get(ctx context.Context, in *LimitDiscountDayStatsWhere, out *LimitDiscountDayStatsResponse) error
	}
	type LimitDiscountDayStatsService struct {
		limitDiscountDayStatsService
	}
	h := &limitDiscountDayStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LimitDiscountDayStatsService{h}, opts...))
}

type limitDiscountDayStatsServiceHandler struct {
	LimitDiscountDayStatsServiceHandler
}

func (h *limitDiscountDayStatsServiceHandler) Search(ctx context.Context, in *LimitDiscountDayStatsWhere, out *LimitDiscountDayStatsResponse) error {
	return h.LimitDiscountDayStatsServiceHandler.Search(ctx, in, out)
}

func (h *limitDiscountDayStatsServiceHandler) Get(ctx context.Context, in *LimitDiscountDayStatsWhere, out *LimitDiscountDayStatsResponse) error {
	return h.LimitDiscountDayStatsServiceHandler.Get(ctx, in, out)
}
