// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: orderFoodService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Type              string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type"` // 订单类型:in-堂食订单,out-外卖订单
	OrderId           int64   `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	TableId           int64   `protobuf:"varint,4,opt,name=table_id,json=tableId,proto3" json:"table_id"`                                  // 桌台ID【堂食订单】
	TableName         string  `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name"`                             // 桌台名称【堂食订单】
	SurchargeType     int32   `protobuf:"varint,6,opt,name=surcharge_type,json=surchargeType,proto3" json:"surcharge_type"`                // 附加费类型【堂食订单】:1-按每位,2-按每单
	SurchargeFee      float32 `protobuf:"fixed32,7,opt,name=surcharge_fee,json=surchargeFee,proto3" json:"surcharge_fee"`                  // 附加费【堂食订单】:X元/每位|每单
	SurchargeFeeName  string  `protobuf:"bytes,8,opt,name=surcharge_fee_name,json=surchargeFeeName,proto3" json:"surcharge_fee_name"`      // 附加费的自定义名称【堂食订单】
	TotalSurchargeFee float32 `protobuf:"fixed32,9,opt,name=total_surcharge_fee,json=totalSurchargeFee,proto3" json:"total_surcharge_fee"` // 总的附加费
	BoxFee            float32 `protobuf:"fixed32,10,opt,name=box_fee,json=boxFee,proto3" json:"box_fee"`                                   // 餐盒费
	GuestNum          int32   `protobuf:"varint,11,opt,name=guest_num,json=guestNum,proto3" json:"guest_num"`                              // 就餐人数
	IsSettlement      bool    `protobuf:"varint,12,opt,name=is_settlement,json=isSettlement,proto3" json:"is_settlement"`
}

func (x *OrderFood) Reset() {
	*x = OrderFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderFoodService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFood) ProtoMessage() {}

func (x *OrderFood) ProtoReflect() protoreflect.Message {
	mi := &file_orderFoodService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFood.ProtoReflect.Descriptor instead.
func (*OrderFood) Descriptor() ([]byte, []int) {
	return file_orderFoodService_proto_rawDescGZIP(), []int{0}
}

func (x *OrderFood) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderFood) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderFood) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderFood) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *OrderFood) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *OrderFood) GetSurchargeType() int32 {
	if x != nil {
		return x.SurchargeType
	}
	return 0
}

func (x *OrderFood) GetSurchargeFee() float32 {
	if x != nil {
		return x.SurchargeFee
	}
	return 0
}

func (x *OrderFood) GetSurchargeFeeName() string {
	if x != nil {
		return x.SurchargeFeeName
	}
	return ""
}

func (x *OrderFood) GetTotalSurchargeFee() float32 {
	if x != nil {
		return x.TotalSurchargeFee
	}
	return 0
}

func (x *OrderFood) GetBoxFee() float32 {
	if x != nil {
		return x.BoxFee
	}
	return 0
}

func (x *OrderFood) GetGuestNum() int32 {
	if x != nil {
		return x.GuestNum
	}
	return 0
}

func (x *OrderFood) GetIsSettlement() bool {
	if x != nil {
		return x.IsSettlement
	}
	return false
}

var File_orderFoodService_proto protoreflect.FileDescriptor

var file_orderFoodService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x22, 0x89, 0x03, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x66, 0x65,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x46, 0x65, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x73, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x46, 0x65, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x72, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x46, 0x65, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x78, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x62, 0x6f, 0x78, 0x46, 0x65, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f,
	0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x73, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orderFoodService_proto_rawDescOnce sync.Once
	file_orderFoodService_proto_rawDescData = file_orderFoodService_proto_rawDesc
)

func file_orderFoodService_proto_rawDescGZIP() []byte {
	file_orderFoodService_proto_rawDescOnce.Do(func() {
		file_orderFoodService_proto_rawDescData = protoimpl.X.CompressGZIP(file_orderFoodService_proto_rawDescData)
	})
	return file_orderFoodService_proto_rawDescData
}

var file_orderFoodService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orderFoodService_proto_goTypes = []interface{}{
	(*OrderFood)(nil), // 0: services.OrderFood
}
var file_orderFoodService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orderFoodService_proto_init() }
func file_orderFoodService_proto_init() {
	if File_orderFoodService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orderFoodService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orderFoodService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderFoodService_proto_goTypes,
		DependencyIndexes: file_orderFoodService_proto_depIdxs,
		MessageInfos:      file_orderFoodService_proto_msgTypes,
	}.Build()
	File_orderFoodService_proto = out.File
	file_orderFoodService_proto_rawDesc = nil
	file_orderFoodService_proto_goTypes = nil
	file_orderFoodService_proto_depIdxs = nil
}
