// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: roomStatusStatsService.proto

package services

import (
	common "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomStatusStatsWhere struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paged    int32  `protobuf:"varint,1,opt,name=paged,proto3" json:"paged"`
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Top      int32  `protobuf:"varint,3,opt,name=top,proto3" json:"top"`
	Date     string `protobuf:"bytes,4,opt,name=date,proto3" json:"date"`
}

func (x *RoomStatusStatsWhere) Reset() {
	*x = RoomStatusStatsWhere{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomStatusStatsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStatusStatsWhere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatusStatsWhere) ProtoMessage() {}

func (x *RoomStatusStatsWhere) ProtoReflect() protoreflect.Message {
	mi := &file_roomStatusStatsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatusStatsWhere.ProtoReflect.Descriptor instead.
func (*RoomStatusStatsWhere) Descriptor() ([]byte, []int) {
	return file_roomStatusStatsService_proto_rawDescGZIP(), []int{0}
}

func (x *RoomStatusStatsWhere) GetPaged() int32 {
	if x != nil {
		return x.Paged
	}
	return 0
}

func (x *RoomStatusStatsWhere) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RoomStatusStatsWhere) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *RoomStatusStatsWhere) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type RoomStatusStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date      string `protobuf:"bytes,1,opt,name=date,proto3" json:"date"`                             // 日期
	TotalNum  int32  `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"total_num"`    // 房间总数
	VacantNum int32  `protobuf:"varint,3,opt,name=vacant_num,json=vacantNum,proto3" json:"vacant_num"` // 空房数量
	UsingNum  int32  `protobuf:"varint,4,opt,name=using_num,json=usingNum,proto3" json:"using_num"`    // 在住数量
	BookNum   int32  `protobuf:"varint,5,opt,name=book_num,json=bookNum,proto3" json:"book_num"`       // 预定数量
	KeepNum   int32  `protobuf:"varint,6,opt,name=keep_num,json=keepNum,proto3" json:"keep_num"`       // 保留房数量
	CleanNum  int32  `protobuf:"varint,7,opt,name=clean_num,json=cleanNum,proto3" json:"clean_num"`    // 净房数量
	DirtyNum  int32  `protobuf:"varint,8,opt,name=dirty_num,json=dirtyNum,proto3" json:"dirty_num"`    // 脏房数量
	RepairNum int32  `protobuf:"varint,9,opt,name=repair_num,json=repairNum,proto3" json:"repair_num"` // 维修房数量
}

func (x *RoomStatusStats) Reset() {
	*x = RoomStatusStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomStatusStatsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStatusStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatusStats) ProtoMessage() {}

func (x *RoomStatusStats) ProtoReflect() protoreflect.Message {
	mi := &file_roomStatusStatsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatusStats.ProtoReflect.Descriptor instead.
func (*RoomStatusStats) Descriptor() ([]byte, []int) {
	return file_roomStatusStatsService_proto_rawDescGZIP(), []int{1}
}

func (x *RoomStatusStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RoomStatusStats) GetTotalNum() int32 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

func (x *RoomStatusStats) GetVacantNum() int32 {
	if x != nil {
		return x.VacantNum
	}
	return 0
}

func (x *RoomStatusStats) GetUsingNum() int32 {
	if x != nil {
		return x.UsingNum
	}
	return 0
}

func (x *RoomStatusStats) GetBookNum() int32 {
	if x != nil {
		return x.BookNum
	}
	return 0
}

func (x *RoomStatusStats) GetKeepNum() int32 {
	if x != nil {
		return x.KeepNum
	}
	return 0
}

func (x *RoomStatusStats) GetCleanNum() int32 {
	if x != nil {
		return x.CleanNum
	}
	return 0
}

func (x *RoomStatusStats) GetDirtyNum() int32 {
	if x != nil {
		return x.DirtyNum
	}
	return 0
}

func (x *RoomStatusStats) GetRepairNum() int32 {
	if x != nil {
		return x.RepairNum
	}
	return 0
}

type RoomStatusStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error  *common.Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error"`
	Info   *common.Info       `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
	Pager  *common.Pager      `protobuf:"bytes,3,opt,name=pager,proto3" json:"pager"`
	Entity *RoomStatusStats   `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity"`
	Items  []*RoomStatusStats `protobuf:"bytes,5,rep,name=items,proto3" json:"items"`
}

func (x *RoomStatusStatsResponse) Reset() {
	*x = RoomStatusStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomStatusStatsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStatusStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStatusStatsResponse) ProtoMessage() {}

func (x *RoomStatusStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roomStatusStatsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStatusStatsResponse.ProtoReflect.Descriptor instead.
func (*RoomStatusStatsResponse) Descriptor() ([]byte, []int) {
	return file_roomStatusStatsService_proto_rawDescGZIP(), []int{2}
}

func (x *RoomStatusStatsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RoomStatusStatsResponse) GetInfo() *common.Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *RoomStatusStatsResponse) GetPager() *common.Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *RoomStatusStatsResponse) GetEntity() *RoomStatusStats {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *RoomStatusStatsResponse) GetItems() []*RoomStatusStats {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_roomStatusStatsService_proto protoreflect.FileDescriptor

var file_roomStatusStatsService_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x14, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x57, 0x68,
	0x65, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x8d, 0x02, 0x0a,
	0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x65, 0x70,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6b, 0x65, 0x65, 0x70,
	0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x4e, 0x75, 0x6d,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x72, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x72, 0x65, 0x70, 0x61, 0x69, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0xe9, 0x01, 0x0a,
	0x17, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x64, 0x0a, 0x16, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x05, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x12, 0x1e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x57, 0x68, 0x65, 0x72, 0x65, 0x1a, 0x21, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roomStatusStatsService_proto_rawDescOnce sync.Once
	file_roomStatusStatsService_proto_rawDescData = file_roomStatusStatsService_proto_rawDesc
)

func file_roomStatusStatsService_proto_rawDescGZIP() []byte {
	file_roomStatusStatsService_proto_rawDescOnce.Do(func() {
		file_roomStatusStatsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomStatusStatsService_proto_rawDescData)
	})
	return file_roomStatusStatsService_proto_rawDescData
}

var file_roomStatusStatsService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_roomStatusStatsService_proto_goTypes = []interface{}{
	(*RoomStatusStatsWhere)(nil),    // 0: services.RoomStatusStatsWhere
	(*RoomStatusStats)(nil),         // 1: services.RoomStatusStats
	(*RoomStatusStatsResponse)(nil), // 2: services.RoomStatusStatsResponse
	(*common.Error)(nil),            // 3: common.Error
	(*common.Info)(nil),             // 4: common.Info
	(*common.Pager)(nil),            // 5: common.Pager
}
var file_roomStatusStatsService_proto_depIdxs = []int32{
	3, // 0: services.RoomStatusStatsResponse.error:type_name -> common.Error
	4, // 1: services.RoomStatusStatsResponse.info:type_name -> common.Info
	5, // 2: services.RoomStatusStatsResponse.pager:type_name -> common.Pager
	1, // 3: services.RoomStatusStatsResponse.entity:type_name -> services.RoomStatusStats
	1, // 4: services.RoomStatusStatsResponse.items:type_name -> services.RoomStatusStats
	0, // 5: services.RoomStatusStatsService.Today:input_type -> services.RoomStatusStatsWhere
	2, // 6: services.RoomStatusStatsService.Today:output_type -> services.RoomStatusStatsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_roomStatusStatsService_proto_init() }
func file_roomStatusStatsService_proto_init() {
	if File_roomStatusStatsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roomStatusStatsService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStatusStatsWhere); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomStatusStatsService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStatusStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roomStatusStatsService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStatusStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomStatusStatsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roomStatusStatsService_proto_goTypes,
		DependencyIndexes: file_roomStatusStatsService_proto_depIdxs,
		MessageInfos:      file_roomStatusStatsService_proto_msgTypes,
	}.Build()
	File_roomStatusStatsService_proto = out.File
	file_roomStatusStatsService_proto_rawDesc = nil
	file_roomStatusStatsService_proto_goTypes = nil
	file_roomStatusStatsService_proto_depIdxs = nil
}
