// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomPriceService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomPriceService service

func NewRoomPriceServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomPriceService service

type RoomPriceService interface {
	Get(ctx context.Context, in *RoomPriceWhere, opts ...client.CallOption) (*RoomPriceResponse, error)
	Save(ctx context.Context, in *RoomPrice, opts ...client.CallOption) (*RoomPriceResponse, error)
}

type roomPriceService struct {
	c    client.Client
	name string
}

func NewRoomPriceService(name string, c client.Client) RoomPriceService {
	return &roomPriceService{
		c:    c,
		name: name,
	}
}

func (c *roomPriceService) Get(ctx context.Context, in *RoomPriceWhere, opts ...client.CallOption) (*RoomPriceResponse, error) {
	req := c.c.NewRequest(c.name, "RoomPriceService.Get", in)
	out := new(RoomPriceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomPriceService) Save(ctx context.Context, in *RoomPrice, opts ...client.CallOption) (*RoomPriceResponse, error) {
	req := c.c.NewRequest(c.name, "RoomPriceService.Save", in)
	out := new(RoomPriceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomPriceService service

type RoomPriceServiceHandler interface {
	Get(context.Context, *RoomPriceWhere, *RoomPriceResponse) error
	Save(context.Context, *RoomPrice, *RoomPriceResponse) error
}

func RegisterRoomPriceServiceHandler(s server.Server, hdlr RoomPriceServiceHandler, opts ...server.HandlerOption) error {
	type roomPriceService interface {
		Get(ctx context.Context, in *RoomPriceWhere, out *RoomPriceResponse) error
		Save(ctx context.Context, in *RoomPrice, out *RoomPriceResponse) error
	}
	type RoomPriceService struct {
		roomPriceService
	}
	h := &roomPriceServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomPriceService{h}, opts...))
}

type roomPriceServiceHandler struct {
	RoomPriceServiceHandler
}

func (h *roomPriceServiceHandler) Get(ctx context.Context, in *RoomPriceWhere, out *RoomPriceResponse) error {
	return h.RoomPriceServiceHandler.Get(ctx, in, out)
}

func (h *roomPriceServiceHandler) Save(ctx context.Context, in *RoomPrice, out *RoomPriceResponse) error {
	return h.RoomPriceServiceHandler.Save(ctx, in, out)
}
