// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomTypeFacilityService.proto

package services

import (
	_ "github.com/geiqin/microkit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomTypeFacilityService service

func NewRoomTypeFacilityServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomTypeFacilityService service

type RoomTypeFacilityService interface {
	Search(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
	List(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
	Get(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
	Create(ctx context.Context, in *RoomTypeFacility, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
	Update(ctx context.Context, in *RoomTypeFacility, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
	Delete(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error)
}

type roomTypeFacilityService struct {
	c    client.Client
	name string
}

func NewRoomTypeFacilityService(name string, c client.Client) RoomTypeFacilityService {
	return &roomTypeFacilityService{
		c:    c,
		name: name,
	}
}

func (c *roomTypeFacilityService) Search(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.Search", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityService) List(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.List", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityService) Get(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.Get", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityService) Create(ctx context.Context, in *RoomTypeFacility, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.Create", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityService) Update(ctx context.Context, in *RoomTypeFacility, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.Update", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityService) Delete(ctx context.Context, in *RoomTypeFacilityWhere, opts ...client.CallOption) (*RoomTypeFacilityResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityService.Delete", in)
	out := new(RoomTypeFacilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomTypeFacilityService service

type RoomTypeFacilityServiceHandler interface {
	Search(context.Context, *RoomTypeFacilityWhere, *RoomTypeFacilityResponse) error
	List(context.Context, *RoomTypeFacilityWhere, *RoomTypeFacilityResponse) error
	Get(context.Context, *RoomTypeFacilityWhere, *RoomTypeFacilityResponse) error
	Create(context.Context, *RoomTypeFacility, *RoomTypeFacilityResponse) error
	Update(context.Context, *RoomTypeFacility, *RoomTypeFacilityResponse) error
	Delete(context.Context, *RoomTypeFacilityWhere, *RoomTypeFacilityResponse) error
}

func RegisterRoomTypeFacilityServiceHandler(s server.Server, hdlr RoomTypeFacilityServiceHandler, opts ...server.HandlerOption) error {
	type roomTypeFacilityService interface {
		Search(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error
		List(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error
		Get(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error
		Create(ctx context.Context, in *RoomTypeFacility, out *RoomTypeFacilityResponse) error
		Update(ctx context.Context, in *RoomTypeFacility, out *RoomTypeFacilityResponse) error
		Delete(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error
	}
	type RoomTypeFacilityService struct {
		roomTypeFacilityService
	}
	h := &roomTypeFacilityServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomTypeFacilityService{h}, opts...))
}

type roomTypeFacilityServiceHandler struct {
	RoomTypeFacilityServiceHandler
}

func (h *roomTypeFacilityServiceHandler) Search(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.Search(ctx, in, out)
}

func (h *roomTypeFacilityServiceHandler) List(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.List(ctx, in, out)
}

func (h *roomTypeFacilityServiceHandler) Get(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.Get(ctx, in, out)
}

func (h *roomTypeFacilityServiceHandler) Create(ctx context.Context, in *RoomTypeFacility, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.Create(ctx, in, out)
}

func (h *roomTypeFacilityServiceHandler) Update(ctx context.Context, in *RoomTypeFacility, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.Update(ctx, in, out)
}

func (h *roomTypeFacilityServiceHandler) Delete(ctx context.Context, in *RoomTypeFacilityWhere, out *RoomTypeFacilityResponse) error {
	return h.RoomTypeFacilityServiceHandler.Delete(ctx, in, out)
}
