// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomBillDetailService.proto

package services

import (
	_ "github.com/geiqin/microkit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomBillDetailService service

func NewRoomBillDetailServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomBillDetailService service

type RoomBillDetailService interface {
	// 查询账单明细
	Search(ctx context.Context, in *RoomBillDetailWhere, opts ...client.CallOption) (*RoomBillDetailResponse, error)
}

type roomBillDetailService struct {
	c    client.Client
	name string
}

func NewRoomBillDetailService(name string, c client.Client) RoomBillDetailService {
	return &roomBillDetailService{
		c:    c,
		name: name,
	}
}

func (c *roomBillDetailService) Search(ctx context.Context, in *RoomBillDetailWhere, opts ...client.CallOption) (*RoomBillDetailResponse, error) {
	req := c.c.NewRequest(c.name, "RoomBillDetailService.Search", in)
	out := new(RoomBillDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomBillDetailService service

type RoomBillDetailServiceHandler interface {
	// 查询账单明细
	Search(context.Context, *RoomBillDetailWhere, *RoomBillDetailResponse) error
}

func RegisterRoomBillDetailServiceHandler(s server.Server, hdlr RoomBillDetailServiceHandler, opts ...server.HandlerOption) error {
	type roomBillDetailService interface {
		Search(ctx context.Context, in *RoomBillDetailWhere, out *RoomBillDetailResponse) error
	}
	type RoomBillDetailService struct {
		roomBillDetailService
	}
	h := &roomBillDetailServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomBillDetailService{h}, opts...))
}

type roomBillDetailServiceHandler struct {
	RoomBillDetailServiceHandler
}

func (h *roomBillDetailServiceHandler) Search(ctx context.Context, in *RoomBillDetailWhere, out *RoomBillDetailResponse) error {
	return h.RoomBillDetailServiceHandler.Search(ctx, in, out)
}
