// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomStatusStatsService.proto

package services

import (
	_ "github.com/geiqin/microkit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomStatusStatsService service

func NewRoomStatusStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomStatusStatsService service

type RoomStatusStatsService interface {
	// 今日房态统计
	Today(ctx context.Context, in *RoomStatusStatsWhere, opts ...client.CallOption) (*RoomStatusStatsResponse, error)
}

type roomStatusStatsService struct {
	c    client.Client
	name string
}

func NewRoomStatusStatsService(name string, c client.Client) RoomStatusStatsService {
	return &roomStatusStatsService{
		c:    c,
		name: name,
	}
}

func (c *roomStatusStatsService) Today(ctx context.Context, in *RoomStatusStatsWhere, opts ...client.CallOption) (*RoomStatusStatsResponse, error) {
	req := c.c.NewRequest(c.name, "RoomStatusStatsService.Today", in)
	out := new(RoomStatusStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomStatusStatsService service

type RoomStatusStatsServiceHandler interface {
	// 今日房态统计
	Today(context.Context, *RoomStatusStatsWhere, *RoomStatusStatsResponse) error
}

func RegisterRoomStatusStatsServiceHandler(s server.Server, hdlr RoomStatusStatsServiceHandler, opts ...server.HandlerOption) error {
	type roomStatusStatsService interface {
		Today(ctx context.Context, in *RoomStatusStatsWhere, out *RoomStatusStatsResponse) error
	}
	type RoomStatusStatsService struct {
		roomStatusStatsService
	}
	h := &roomStatusStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomStatusStatsService{h}, opts...))
}

type roomStatusStatsServiceHandler struct {
	RoomStatusStatsServiceHandler
}

func (h *roomStatusStatsServiceHandler) Today(ctx context.Context, in *RoomStatusStatsWhere, out *RoomStatusStatsResponse) error {
	return h.RoomStatusStatsServiceHandler.Today(ctx, in, out)
}
