// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomStatusMaintainCalendarService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomStatusMaintainCalendarService service

func NewRoomStatusMaintainCalendarServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomStatusMaintainCalendarService service

type RoomStatusMaintainCalendarService interface {
	List(ctx context.Context, in *RoomStatusMaintainCalendarWhere, opts ...client.CallOption) (*RoomStatusMaintainCalendarResponse, error)
}

type roomStatusMaintainCalendarService struct {
	c    client.Client
	name string
}

func NewRoomStatusMaintainCalendarService(name string, c client.Client) RoomStatusMaintainCalendarService {
	return &roomStatusMaintainCalendarService{
		c:    c,
		name: name,
	}
}

func (c *roomStatusMaintainCalendarService) List(ctx context.Context, in *RoomStatusMaintainCalendarWhere, opts ...client.CallOption) (*RoomStatusMaintainCalendarResponse, error) {
	req := c.c.NewRequest(c.name, "RoomStatusMaintainCalendarService.List", in)
	out := new(RoomStatusMaintainCalendarResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomStatusMaintainCalendarService service

type RoomStatusMaintainCalendarServiceHandler interface {
	List(context.Context, *RoomStatusMaintainCalendarWhere, *RoomStatusMaintainCalendarResponse) error
}

func RegisterRoomStatusMaintainCalendarServiceHandler(s server.Server, hdlr RoomStatusMaintainCalendarServiceHandler, opts ...server.HandlerOption) error {
	type roomStatusMaintainCalendarService interface {
		List(ctx context.Context, in *RoomStatusMaintainCalendarWhere, out *RoomStatusMaintainCalendarResponse) error
	}
	type RoomStatusMaintainCalendarService struct {
		roomStatusMaintainCalendarService
	}
	h := &roomStatusMaintainCalendarServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomStatusMaintainCalendarService{h}, opts...))
}

type roomStatusMaintainCalendarServiceHandler struct {
	RoomStatusMaintainCalendarServiceHandler
}

func (h *roomStatusMaintainCalendarServiceHandler) List(ctx context.Context, in *RoomStatusMaintainCalendarWhere, out *RoomStatusMaintainCalendarResponse) error {
	return h.RoomStatusMaintainCalendarServiceHandler.List(ctx, in, out)
}
