// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomTypeTagService.proto

package services

import (
	_ "github.com/geiqin/microkit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomTypeTagService service

func NewRoomTypeTagServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomTypeTagService service

type RoomTypeTagService interface {
	Search(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error)
	List(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error)
	Get(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error)
	Create(ctx context.Context, in *RoomTypeTag, opts ...client.CallOption) (*RoomTypeTagResponse, error)
	Update(ctx context.Context, in *RoomTypeTag, opts ...client.CallOption) (*RoomTypeTagResponse, error)
	Delete(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error)
}

type roomTypeTagService struct {
	c    client.Client
	name string
}

func NewRoomTypeTagService(name string, c client.Client) RoomTypeTagService {
	return &roomTypeTagService{
		c:    c,
		name: name,
	}
}

func (c *roomTypeTagService) Search(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.Search", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeTagService) List(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.List", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeTagService) Get(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.Get", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeTagService) Create(ctx context.Context, in *RoomTypeTag, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.Create", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeTagService) Update(ctx context.Context, in *RoomTypeTag, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.Update", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeTagService) Delete(ctx context.Context, in *RoomTypeTagWhere, opts ...client.CallOption) (*RoomTypeTagResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeTagService.Delete", in)
	out := new(RoomTypeTagResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomTypeTagService service

type RoomTypeTagServiceHandler interface {
	Search(context.Context, *RoomTypeTagWhere, *RoomTypeTagResponse) error
	List(context.Context, *RoomTypeTagWhere, *RoomTypeTagResponse) error
	Get(context.Context, *RoomTypeTagWhere, *RoomTypeTagResponse) error
	Create(context.Context, *RoomTypeTag, *RoomTypeTagResponse) error
	Update(context.Context, *RoomTypeTag, *RoomTypeTagResponse) error
	Delete(context.Context, *RoomTypeTagWhere, *RoomTypeTagResponse) error
}

func RegisterRoomTypeTagServiceHandler(s server.Server, hdlr RoomTypeTagServiceHandler, opts ...server.HandlerOption) error {
	type roomTypeTagService interface {
		Search(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error
		List(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error
		Get(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error
		Create(ctx context.Context, in *RoomTypeTag, out *RoomTypeTagResponse) error
		Update(ctx context.Context, in *RoomTypeTag, out *RoomTypeTagResponse) error
		Delete(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error
	}
	type RoomTypeTagService struct {
		roomTypeTagService
	}
	h := &roomTypeTagServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomTypeTagService{h}, opts...))
}

type roomTypeTagServiceHandler struct {
	RoomTypeTagServiceHandler
}

func (h *roomTypeTagServiceHandler) Search(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.Search(ctx, in, out)
}

func (h *roomTypeTagServiceHandler) List(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.List(ctx, in, out)
}

func (h *roomTypeTagServiceHandler) Get(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.Get(ctx, in, out)
}

func (h *roomTypeTagServiceHandler) Create(ctx context.Context, in *RoomTypeTag, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.Create(ctx, in, out)
}

func (h *roomTypeTagServiceHandler) Update(ctx context.Context, in *RoomTypeTag, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.Update(ctx, in, out)
}

func (h *roomTypeTagServiceHandler) Delete(ctx context.Context, in *RoomTypeTagWhere, out *RoomTypeTagResponse) error {
	return h.RoomTypeTagServiceHandler.Delete(ctx, in, out)
}
