// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: roomPriceVipcardService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomPriceVipcard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomPriceId int64   `protobuf:"varint,2,opt,name=room_price_id,json=roomPriceId,proto3" json:"room_price_id,omitempty"`
	VipcardId   int32   `protobuf:"varint,3,opt,name=vipcard_id,json=vipcardId,proto3" json:"vipcard_id,omitempty"`
	Price       float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	VipcardName string  `protobuf:"bytes,5,opt,name=vipcard_name,json=vipcardName,proto3" json:"vipcard_name,omitempty"`
}

func (x *RoomPriceVipcard) Reset() {
	*x = RoomPriceVipcard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roomPriceVipcardService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPriceVipcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPriceVipcard) ProtoMessage() {}

func (x *RoomPriceVipcard) ProtoReflect() protoreflect.Message {
	mi := &file_roomPriceVipcardService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPriceVipcard.ProtoReflect.Descriptor instead.
func (*RoomPriceVipcard) Descriptor() ([]byte, []int) {
	return file_roomPriceVipcardService_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPriceVipcard) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomPriceVipcard) GetRoomPriceId() int64 {
	if x != nil {
		return x.RoomPriceId
	}
	return 0
}

func (x *RoomPriceVipcard) GetVipcardId() int32 {
	if x != nil {
		return x.VipcardId
	}
	return 0
}

func (x *RoomPriceVipcard) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RoomPriceVipcard) GetVipcardName() string {
	if x != nil {
		return x.VipcardName
	}
	return ""
}

var File_roomPriceVipcardService_proto protoreflect.FileDescriptor

var file_roomPriceVipcardService_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x56, 0x69, 0x70, 0x63, 0x61,
	0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x10, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x56, 0x69, 0x70, 0x63, 0x61, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0d, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x70, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x69, 0x70, 0x63, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x69, 0x70, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76,
	0x69, 0x70, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roomPriceVipcardService_proto_rawDescOnce sync.Once
	file_roomPriceVipcardService_proto_rawDescData = file_roomPriceVipcardService_proto_rawDesc
)

func file_roomPriceVipcardService_proto_rawDescGZIP() []byte {
	file_roomPriceVipcardService_proto_rawDescOnce.Do(func() {
		file_roomPriceVipcardService_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomPriceVipcardService_proto_rawDescData)
	})
	return file_roomPriceVipcardService_proto_rawDescData
}

var file_roomPriceVipcardService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_roomPriceVipcardService_proto_goTypes = []interface{}{
	(*RoomPriceVipcard)(nil), // 0: services.RoomPriceVipcard
}
var file_roomPriceVipcardService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_roomPriceVipcardService_proto_init() }
func file_roomPriceVipcardService_proto_init() {
	if File_roomPriceVipcardService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roomPriceVipcardService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPriceVipcard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomPriceVipcardService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roomPriceVipcardService_proto_goTypes,
		DependencyIndexes: file_roomPriceVipcardService_proto_depIdxs,
		MessageInfos:      file_roomPriceVipcardService_proto_msgTypes,
	}.Build()
	File_roomPriceVipcardService_proto = out.File
	file_roomPriceVipcardService_proto_rawDesc = nil
	file_roomPriceVipcardService_proto_goTypes = nil
	file_roomPriceVipcardService_proto_depIdxs = nil
}
