// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: roomTypeFacilityCatService.proto

package services

import (
	_ "github.com/geiqin/microkit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RoomTypeFacilityCatService service

func NewRoomTypeFacilityCatServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RoomTypeFacilityCatService service

type RoomTypeFacilityCatService interface {
	Search(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	List(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	Get(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	Create(ctx context.Context, in *RoomTypeFacilityCat, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	Update(ctx context.Context, in *RoomTypeFacilityCat, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	Delete(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
	Tree(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error)
}

type roomTypeFacilityCatService struct {
	c    client.Client
	name string
}

func NewRoomTypeFacilityCatService(name string, c client.Client) RoomTypeFacilityCatService {
	return &roomTypeFacilityCatService{
		c:    c,
		name: name,
	}
}

func (c *roomTypeFacilityCatService) Search(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Search", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) List(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.List", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) Get(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Get", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) Create(ctx context.Context, in *RoomTypeFacilityCat, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Create", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) Update(ctx context.Context, in *RoomTypeFacilityCat, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Update", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) Delete(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Delete", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomTypeFacilityCatService) Tree(ctx context.Context, in *RoomTypeFacilityCatWhere, opts ...client.CallOption) (*RoomTypeFacilityCatResponse, error) {
	req := c.c.NewRequest(c.name, "RoomTypeFacilityCatService.Tree", in)
	out := new(RoomTypeFacilityCatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoomTypeFacilityCatService service

type RoomTypeFacilityCatServiceHandler interface {
	Search(context.Context, *RoomTypeFacilityCatWhere, *RoomTypeFacilityCatResponse) error
	List(context.Context, *RoomTypeFacilityCatWhere, *RoomTypeFacilityCatResponse) error
	Get(context.Context, *RoomTypeFacilityCatWhere, *RoomTypeFacilityCatResponse) error
	Create(context.Context, *RoomTypeFacilityCat, *RoomTypeFacilityCatResponse) error
	Update(context.Context, *RoomTypeFacilityCat, *RoomTypeFacilityCatResponse) error
	Delete(context.Context, *RoomTypeFacilityCatWhere, *RoomTypeFacilityCatResponse) error
	Tree(context.Context, *RoomTypeFacilityCatWhere, *RoomTypeFacilityCatResponse) error
}

func RegisterRoomTypeFacilityCatServiceHandler(s server.Server, hdlr RoomTypeFacilityCatServiceHandler, opts ...server.HandlerOption) error {
	type roomTypeFacilityCatService interface {
		Search(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error
		List(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error
		Get(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error
		Create(ctx context.Context, in *RoomTypeFacilityCat, out *RoomTypeFacilityCatResponse) error
		Update(ctx context.Context, in *RoomTypeFacilityCat, out *RoomTypeFacilityCatResponse) error
		Delete(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error
		Tree(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error
	}
	type RoomTypeFacilityCatService struct {
		roomTypeFacilityCatService
	}
	h := &roomTypeFacilityCatServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RoomTypeFacilityCatService{h}, opts...))
}

type roomTypeFacilityCatServiceHandler struct {
	RoomTypeFacilityCatServiceHandler
}

func (h *roomTypeFacilityCatServiceHandler) Search(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Search(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) List(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.List(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) Get(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Get(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) Create(ctx context.Context, in *RoomTypeFacilityCat, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Create(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) Update(ctx context.Context, in *RoomTypeFacilityCat, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Update(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) Delete(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Delete(ctx, in, out)
}

func (h *roomTypeFacilityCatServiceHandler) Tree(ctx context.Context, in *RoomTypeFacilityCatWhere, out *RoomTypeFacilityCatResponse) error {
	return h.RoomTypeFacilityCatServiceHandler.Tree(ctx, in, out)
}
