// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: storeMenuService.proto

package services

import (
	_ "geiqin.saas.mts/app/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StoreMenuService service

func NewStoreMenuServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StoreMenuService service

type StoreMenuService interface {
}

type storeMenuService struct {
	c    client.Client
	name string
}

func NewStoreMenuService(name string, c client.Client) StoreMenuService {
	return &storeMenuService{
		c:    c,
		name: name,
	}
}

// Server API for StoreMenuService service

type StoreMenuServiceHandler interface {
}

func RegisterStoreMenuServiceHandler(s server.Server, hdlr StoreMenuServiceHandler, opts ...server.HandlerOption) error {
	type storeMenuService interface {
	}
	type StoreMenuService struct {
		storeMenuService
	}
	h := &storeMenuServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StoreMenuService{h}, opts...))
}

type storeMenuServiceHandler struct {
	StoreMenuServiceHandler
}
