// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: codeDayStatsDetailService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CodeDayStatsDetailService service

func NewCodeDayStatsDetailServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CodeDayStatsDetailService service

type CodeDayStatsDetailService interface {
	Get(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error)
	Search(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error)
	List(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error)
}

type codeDayStatsDetailService struct {
	c    client.Client
	name string
}

func NewCodeDayStatsDetailService(name string, c client.Client) CodeDayStatsDetailService {
	return &codeDayStatsDetailService{
		c:    c,
		name: name,
	}
}

func (c *codeDayStatsDetailService) Get(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error) {
	req := c.c.NewRequest(c.name, "CodeDayStatsDetailService.Get", in)
	out := new(CodeDayStatsDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeDayStatsDetailService) Search(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error) {
	req := c.c.NewRequest(c.name, "CodeDayStatsDetailService.Search", in)
	out := new(CodeDayStatsDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeDayStatsDetailService) List(ctx context.Context, in *CodeDayStatsDetailWhere, opts ...client.CallOption) (*CodeDayStatsDetailResponse, error) {
	req := c.c.NewRequest(c.name, "CodeDayStatsDetailService.List", in)
	out := new(CodeDayStatsDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CodeDayStatsDetailService service

type CodeDayStatsDetailServiceHandler interface {
	Get(context.Context, *CodeDayStatsDetailWhere, *CodeDayStatsDetailResponse) error
	Search(context.Context, *CodeDayStatsDetailWhere, *CodeDayStatsDetailResponse) error
	List(context.Context, *CodeDayStatsDetailWhere, *CodeDayStatsDetailResponse) error
}

func RegisterCodeDayStatsDetailServiceHandler(s server.Server, hdlr CodeDayStatsDetailServiceHandler, opts ...server.HandlerOption) error {
	type codeDayStatsDetailService interface {
		Get(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error
		Search(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error
		List(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error
	}
	type CodeDayStatsDetailService struct {
		codeDayStatsDetailService
	}
	h := &codeDayStatsDetailServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CodeDayStatsDetailService{h}, opts...))
}

type codeDayStatsDetailServiceHandler struct {
	CodeDayStatsDetailServiceHandler
}

func (h *codeDayStatsDetailServiceHandler) Get(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error {
	return h.CodeDayStatsDetailServiceHandler.Get(ctx, in, out)
}

func (h *codeDayStatsDetailServiceHandler) Search(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error {
	return h.CodeDayStatsDetailServiceHandler.Search(ctx, in, out)
}

func (h *codeDayStatsDetailServiceHandler) List(ctx context.Context, in *CodeDayStatsDetailWhere, out *CodeDayStatsDetailResponse) error {
	return h.CodeDayStatsDetailServiceHandler.List(ctx, in, out)
}
