// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: codeStatsService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CodeStatsService service

func NewCodeStatsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CodeStatsService service

type CodeStatsService interface {
	Get(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*CodeStatsResponse, error)
}

type codeStatsService struct {
	c    client.Client
	name string
}

func NewCodeStatsService(name string, c client.Client) CodeStatsService {
	return &codeStatsService{
		c:    c,
		name: name,
	}
}

func (c *codeStatsService) Get(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*CodeStatsResponse, error) {
	req := c.c.NewRequest(c.name, "CodeStatsService.Get", in)
	out := new(CodeStatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CodeStatsService service

type CodeStatsServiceHandler interface {
	Get(context.Context, *common.Empty, *CodeStatsResponse) error
}

func RegisterCodeStatsServiceHandler(s server.Server, hdlr CodeStatsServiceHandler, opts ...server.HandlerOption) error {
	type codeStatsService interface {
		Get(ctx context.Context, in *common.Empty, out *CodeStatsResponse) error
	}
	type CodeStatsService struct {
		codeStatsService
	}
	h := &codeStatsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CodeStatsService{h}, opts...))
}

type codeStatsServiceHandler struct {
	CodeStatsServiceHandler
}

func (h *codeStatsServiceHandler) Get(ctx context.Context, in *common.Empty, out *CodeStatsResponse) error {
	return h.CodeStatsServiceHandler.Get(ctx, in, out)
}
