// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: metaFieldService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MetaFieldService service

func NewMetaFieldServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MetaFieldService service

type MetaFieldService interface {
	Create(ctx context.Context, in *MetaField, opts ...client.CallOption) (*MetaFieldResponse, error)
	Update(ctx context.Context, in *MetaField, opts ...client.CallOption) (*MetaFieldResponse, error)
	Search(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error)
	List(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error)
	Delete(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error)
	Get(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error)
}

type metaFieldService struct {
	c    client.Client
	name string
}

func NewMetaFieldService(name string, c client.Client) MetaFieldService {
	return &metaFieldService{
		c:    c,
		name: name,
	}
}

func (c *metaFieldService) Create(ctx context.Context, in *MetaField, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.Create", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaFieldService) Update(ctx context.Context, in *MetaField, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.Update", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaFieldService) Search(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.Search", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaFieldService) List(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.List", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaFieldService) Delete(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.Delete", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaFieldService) Get(ctx context.Context, in *MetaFieldWhere, opts ...client.CallOption) (*MetaFieldResponse, error) {
	req := c.c.NewRequest(c.name, "MetaFieldService.Get", in)
	out := new(MetaFieldResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MetaFieldService service

type MetaFieldServiceHandler interface {
	Create(context.Context, *MetaField, *MetaFieldResponse) error
	Update(context.Context, *MetaField, *MetaFieldResponse) error
	Search(context.Context, *MetaFieldWhere, *MetaFieldResponse) error
	List(context.Context, *MetaFieldWhere, *MetaFieldResponse) error
	Delete(context.Context, *MetaFieldWhere, *MetaFieldResponse) error
	Get(context.Context, *MetaFieldWhere, *MetaFieldResponse) error
}

func RegisterMetaFieldServiceHandler(s server.Server, hdlr MetaFieldServiceHandler, opts ...server.HandlerOption) error {
	type metaFieldService interface {
		Create(ctx context.Context, in *MetaField, out *MetaFieldResponse) error
		Update(ctx context.Context, in *MetaField, out *MetaFieldResponse) error
		Search(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error
		List(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error
		Delete(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error
		Get(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error
	}
	type MetaFieldService struct {
		metaFieldService
	}
	h := &metaFieldServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MetaFieldService{h}, opts...))
}

type metaFieldServiceHandler struct {
	MetaFieldServiceHandler
}

func (h *metaFieldServiceHandler) Create(ctx context.Context, in *MetaField, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.Create(ctx, in, out)
}

func (h *metaFieldServiceHandler) Update(ctx context.Context, in *MetaField, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.Update(ctx, in, out)
}

func (h *metaFieldServiceHandler) Search(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.Search(ctx, in, out)
}

func (h *metaFieldServiceHandler) List(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.List(ctx, in, out)
}

func (h *metaFieldServiceHandler) Delete(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.Delete(ctx, in, out)
}

func (h *metaFieldServiceHandler) Get(ctx context.Context, in *MetaFieldWhere, out *MetaFieldResponse) error {
	return h.MetaFieldServiceHandler.Get(ctx, in, out)
}
