// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: productService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ProductService service

func NewProductServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ProductService service

type ProductService interface {
	Create(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
	Update(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error)
	Search(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error)
	Delete(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error)
	Get(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) Create(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Create", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Update(ctx context.Context, in *Product, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Update", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Search(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Search", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Delete(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Delete", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) Get(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "ProductService.Get", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	Create(context.Context, *Product, *ProductResponse) error
	Update(context.Context, *Product, *ProductResponse) error
	Search(context.Context, *ProductWhere, *ProductResponse) error
	Delete(context.Context, *ProductWhere, *ProductResponse) error
	Get(context.Context, *ProductWhere, *ProductResponse) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) error {
	type productService interface {
		Create(ctx context.Context, in *Product, out *ProductResponse) error
		Update(ctx context.Context, in *Product, out *ProductResponse) error
		Search(ctx context.Context, in *ProductWhere, out *ProductResponse) error
		Delete(ctx context.Context, in *ProductWhere, out *ProductResponse) error
		Get(ctx context.Context, in *ProductWhere, out *ProductResponse) error
	}
	type ProductService struct {
		productService
	}
	h := &productServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductService{h}, opts...))
}

type productServiceHandler struct {
	ProductServiceHandler
}

func (h *productServiceHandler) Create(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.Create(ctx, in, out)
}

func (h *productServiceHandler) Update(ctx context.Context, in *Product, out *ProductResponse) error {
	return h.ProductServiceHandler.Update(ctx, in, out)
}

func (h *productServiceHandler) Search(ctx context.Context, in *ProductWhere, out *ProductResponse) error {
	return h.ProductServiceHandler.Search(ctx, in, out)
}

func (h *productServiceHandler) Delete(ctx context.Context, in *ProductWhere, out *ProductResponse) error {
	return h.ProductServiceHandler.Delete(ctx, in, out)
}

func (h *productServiceHandler) Get(ctx context.Context, in *ProductWhere, out *ProductResponse) error {
	return h.ProductServiceHandler.Get(ctx, in, out)
}

// Api Endpoints for FrontProductService service

func NewFrontProductServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FrontProductService service

type FrontProductService interface {
	Search(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error)
	Get(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error)
}

type frontProductService struct {
	c    client.Client
	name string
}

func NewFrontProductService(name string, c client.Client) FrontProductService {
	return &frontProductService{
		c:    c,
		name: name,
	}
}

func (c *frontProductService) Search(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "FrontProductService.Search", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontProductService) Get(ctx context.Context, in *ProductWhere, opts ...client.CallOption) (*ProductResponse, error) {
	req := c.c.NewRequest(c.name, "FrontProductService.Get", in)
	out := new(ProductResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontProductService service

type FrontProductServiceHandler interface {
	Search(context.Context, *ProductWhere, *ProductResponse) error
	Get(context.Context, *ProductWhere, *ProductResponse) error
}

func RegisterFrontProductServiceHandler(s server.Server, hdlr FrontProductServiceHandler, opts ...server.HandlerOption) error {
	type frontProductService interface {
		Search(ctx context.Context, in *ProductWhere, out *ProductResponse) error
		Get(ctx context.Context, in *ProductWhere, out *ProductResponse) error
	}
	type FrontProductService struct {
		frontProductService
	}
	h := &frontProductServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FrontProductService{h}, opts...))
}

type frontProductServiceHandler struct {
	FrontProductServiceHandler
}

func (h *frontProductServiceHandler) Search(ctx context.Context, in *ProductWhere, out *ProductResponse) error {
	return h.FrontProductServiceHandler.Search(ctx, in, out)
}

func (h *frontProductServiceHandler) Get(ctx context.Context, in *ProductWhere, out *ProductResponse) error {
	return h.FrontProductServiceHandler.Get(ctx, in, out)
}
