// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: productMetaService.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProductMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ProductId      int64      `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id"`
	MetaFieldId    int32      `protobuf:"varint,3,opt,name=meta_field_id,json=metaFieldId,proto3" json:"meta_field_id"`
	MetaFieldValue string     `protobuf:"bytes,4,opt,name=meta_field_value,json=metaFieldValue,proto3" json:"meta_field_value"`
	MetaField      *MetaField `protobuf:"bytes,5,opt,name=meta_field,json=metaField,proto3" json:"meta_field"`
}

func (x *ProductMeta) Reset() {
	*x = ProductMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_productMetaService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMeta) ProtoMessage() {}

func (x *ProductMeta) ProtoReflect() protoreflect.Message {
	mi := &file_productMetaService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMeta.ProtoReflect.Descriptor instead.
func (*ProductMeta) Descriptor() ([]byte, []int) {
	return file_productMetaService_proto_rawDescGZIP(), []int{0}
}

func (x *ProductMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductMeta) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductMeta) GetMetaFieldId() int32 {
	if x != nil {
		return x.MetaFieldId
	}
	return 0
}

func (x *ProductMeta) GetMetaFieldValue() string {
	if x != nil {
		return x.MetaFieldValue
	}
	return ""
}

func (x *ProductMeta) GetMetaField() *MetaField {
	if x != nil {
		return x.MetaField
	}
	return nil
}

var File_productMetaService_proto protoreflect.FileDescriptor

var file_productMetaService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x1a, 0x16, 0x6d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6d,
	0x65, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x10, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_productMetaService_proto_rawDescOnce sync.Once
	file_productMetaService_proto_rawDescData = file_productMetaService_proto_rawDesc
)

func file_productMetaService_proto_rawDescGZIP() []byte {
	file_productMetaService_proto_rawDescOnce.Do(func() {
		file_productMetaService_proto_rawDescData = protoimpl.X.CompressGZIP(file_productMetaService_proto_rawDescData)
	})
	return file_productMetaService_proto_rawDescData
}

var file_productMetaService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_productMetaService_proto_goTypes = []interface{}{
	(*ProductMeta)(nil), // 0: services.ProductMeta
	(*MetaField)(nil),   // 1: services.MetaField
}
var file_productMetaService_proto_depIdxs = []int32{
	1, // 0: services.ProductMeta.meta_field:type_name -> services.MetaField
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_productMetaService_proto_init() }
func file_productMetaService_proto_init() {
	if File_productMetaService_proto != nil {
		return
	}
	file_metaFieldService_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_productMetaService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_productMetaService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_productMetaService_proto_goTypes,
		DependencyIndexes: file_productMetaService_proto_depIdxs,
		MessageInfos:      file_productMetaService_proto_msgTypes,
	}.Build()
	File_productMetaService_proto = out.File
	file_productMetaService_proto_rawDesc = nil
	file_productMetaService_proto_goTypes = nil
	file_productMetaService_proto_depIdxs = nil
}
